const { createClient } = require('@supabase/supabase-js')
require('dotenv').config({ path: '.env.local' })

const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL
const SERVICE_ROLE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY

const supabase = createClient(SUPABASE_URL, SERVICE_ROLE_KEY, {
    auth: { autoRefreshToken: false, persistSession: false },
})

async function deleteSeededUsers() {
    console.log('🗑️  Finding seeded profiles based on UI-Avatars URL...\n')

    // Find all profiles that have the ui-avatars URL pattern generated by the seed script
    const { data: profiles, error } = await supabase
        .from('profiles')
        .select('user_id, full_name, avatar_url')
        .like('avatar_url', '%ui-avatars.com%')

    if (error) {
        console.error("Error fetching profiles:", error)
        return
    }

    console.log(`Found ${profiles.length} seeded profiles to delete.`)

    if (profiles.length === 0) return

    let deleted = 0
    let errors = 0

    // Delete each user from Auth (this cascades to profiles)
    for (const profile of profiles) {
        if (!profile.user_id) continue

        const { error: deleteError } = await supabase.auth.admin.deleteUser(profile.user_id)

        if (deleteError) {
            console.error(`Failed to delete user ID ${profile.user_id} (${profile.full_name}):`, deleteError.message)
            errors++
        } else {
            process.stdout.write(`✅ Deleted seeded user: ${profile.full_name} (${profile.user_id})\n`)
            deleted++
        }

        await new Promise((r) => setTimeout(r, 100))
    }

    console.log(`\n✨ Deletion complete!`)
    console.log(`   ✅ ${deleted} accounts deleted`)
    if (errors > 0) console.log(`   ⚠️ ${errors} errors occurred`)
}

deleteSeededUsers()
